### ISSUE TITLE
[Feature Request] Start usercode count from X

### ISSUE THREAD

**Issue by roflmao** [firstof9/lock-manager#1]
**Is your feature request related to a problem? Please describe.**
My lock (idlock 150,  https://idlock.no/wp-content/uploads/2018/08/IDLock150_ZWave_UserManual_v2.1.pdf) has reserved usercodes from zwave slot 60+

**Describe the solution you'd like**
Make ex a 10 code setup count from X

**Comment by firstof9** [comment]
Feature in 0.0.3
